PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?cert ?uValue ?windowRatio
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:globalHeatTransferCoeff ?uQV ;
          edintcee:windowAreaRatio ?wQV .
    ?uQV qudt:numericValue ?uValue .
    ?wQV qudt:numericValue ?windowRatio .
}
