PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX esadm: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>

SELECT ?ccaa (COUNT(?cert) AS ?numCertificates)
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:registrationAutonomousCommunity ?ccaaUri .
    ?ccaaUri a esadm:Autonomia ;
             rdfs:label ?ccaa .
}
GROUP BY ?ccaa
ORDER BY DESC(?numCertificates)
