PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?cert ?rec ?desc ?savingPct ?savingKwh
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasRecommendation ?rec .
    ?rec edintcee:recommendationDescription ?desc ;
         edintcee:estimatedSavingPct ?spctQV ;
         edintcee:estimatedSavingKwh ?skwhQV .
    ?spctQV qudt:numericValue ?savingPct .
    ?skwhQV qudt:numericValue ?savingKwh .
}
