PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?cert ?rec ?desc ?payback ?cost
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasRecommendation ?rec .
    ?rec edintcee:recommendationDescription ?desc ;
         edintcee:paybackPeriod ?ppQV ;
         edintcee:estimatedCost ?ecQV .
    ?ppQV qudt:numericValue ?payback .
    ?ecQV qudt:numericValue ?cost .
}
