PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?cert ?epNRE ?co2
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasRating ?rating .
    ?rating edintcee:primaryEnergyNonRenewable ?epNREqv ;
            edintcee:co2Emissions ?co2qv .
    ?epNREqv qudt:numericValue ?epNRE .
    ?co2qv qudt:numericValue ?co2 .
}
ORDER BY DESC(?epNRE)
