PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX esdir: <http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/direccion-postal#>
PREFIX schema: <http://schema.org/>

SELECT ?municipality ?ratingLetter (COUNT(?cert) AS ?numCertificates)
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasObservedAddress ?addr ;
          edintcee:hasRating ?rating .
    ?addr a esdir:DireccionPostal ;
          schema:addressLocality ?municipality .
    ?rating edintcee:ratingLetter ?letterConcept .
    ?letterConcept rdfs:label ?ratingLetter .
}
GROUP BY ?municipality ?ratingLetter
ORDER BY ?municipality ?ratingLetter
