# CQ-REC-02: ¿Cuál es el plazo de recuperación y coste estimado de las recomendaciones?

PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>

SELECT ?cert ?recDesc ?payback ?cost
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasRecommendation ?rec .
    ?rec edintcee:recommendationDescription ?recDesc ;
         edintcee:paybackPeriod ?payback ;
         edintcee:estimatedCost ?cost .
}
ORDER BY ?payback
