PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?cert ?heatingCons ?coolingCons ?dhwCons ?lightCons
WHERE {
    ?cert a edintcee:EnergyCertificate ;
          edintcee:hasRating ?rating .
    ?rating edintcee:heatingConsumption ?hqv ;
            edintcee:coolingConsumption ?cqv ;
            edintcee:dhwConsumption ?dqv ;
            edintcee:lightingConsumption ?lqv .
    ?hqv qudt:numericValue ?heatingCons .
    ?cqv qudt:numericValue ?coolingCons .
    ?dqv qudt:numericValue ?dhwCons .
    ?lqv qudt:numericValue ?lightCons .
}
