PREFIX edintcee: <http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

ASK {
    ?rating a edintcee:EnergyRating .
    OPTIONAL { ?rating edintcee:primaryEnergyNonRenewable ?epqv .
               ?epqv qudt:numericValue ?epNR }
    OPTIONAL { ?rating edintcee:co2Emissions ?co2qv .
               ?co2qv qudt:numericValue ?co2 }
    FILTER (BOUND(?epNR) && BOUND(?co2))
}
