abstract=Esta ontología modela los certificados de eficiencia energética de edificios según el Real Decreto 390/2021 para habilitar la interoperabilidad de datos de CEE en el contexto de los datos enlazados (Linked Data).
ontologyTitle=Ontología de Certificados de Eficiencia Energética de Edificios
ontologyPrefix=edintcee
ontologyNamespaceURI=http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/
ontologyName=certificado-energetico
thisVersionURI=http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/0.1.0
latestVersionURI=http://vocab.linkeddata.es/datosabiertos/def/sectorpublico/cee/
#previousVersionURI=
ontologyRevisionNumber=0.1.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=Creative Commons Attribution 4.0 International
licenseIconURL=https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg
citeAs=Ontología de Certificados de Eficiencia Energética de Edificios. Revision: 0.1.0.
DOI=
status=Ontology Specification
backwardsCompatibleWith=
publisher=FEMP
publisherURI=https://www.femp.es/
publisherInstitution=Federación Española de Municipios y Provincias
publisherInstitutionURI=https://www.femp.es/
authors=FEMP;Oscar Corcho;Edna Ruckhaus;Daniel Doña;Lucía Sánchez;Maria del Socorro Bernardos
authorsURI=
authorsInstitution=Ontology Engineering Group, UPM
authorsInstitutionURI=https://oeg.fi.upm.es/
contributors=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.xml
TurtleSerialization=ontology.ttl
N3Serialization=ontology.nt
JSONLDSerialization=ontology.json
